# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admin',
            new_name='admin_name',
        ),
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
