# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180508_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reason',
            field=models.CharField(choices=[(b'Increase Revenue', b'Increase Revenue'), (b'Respect to parents', b'Respect to parents'), (b'Improve Living', b'Improve Living'), (b'Education', b'Education'), (b'Other Reason', b'Other Reason')], max_length=255),
        ),
    ]
